---
name: 'Hello World'
description: 'Greet someone'
inputs:
  dir:
    description: 'Directory'
    required: true
    default: 'workdir'
runs:
  using: "composite"
  steps:
    - name: Demo step mkdir
      shell: bash
      run: |
        pwd
        mkdir -p --verbose ${{ inputs.dir }}
        find .

    - name: Demo step find
      working-directory: ${{ inputs.dir }}
      shell: bash
      run: |
        pwd
        find .
