# SPDX-License-Identifier: GPL-2.0 OR copyleft-next-0.3.1
#
# Most simple Linux kernel subsystems can be tested with this target
# test setup. For more elaborates tests look for a topic branch under the
# kdevops-ci tree. For example to test a filesystem look at the fstests
# branch.

name: Run generic kdevops CI tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:  # Allow manual triggering

jobs:
  setup:
    uses: ./.github/workflows/kdevops-init.yml
    secrets: inherit

  run-tests:
    needs: setup
    name: Run CI tests
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Run CI tests
        run: |
          cd kdevops
          nohup stdbuf -oL bash -c 'make ci-test' > ci.log 2>&1 &
          echo $! > ci.pid
          CI_WATCHDOG="scripts/workflows/generic/crash_watchdog.py"
          while kill -0 $(cat ci.pid) 2> /dev/null; do
            $CI_WATCHDOG || echo watchdog barfed
            sleep 60
          done

          # Check for kernel test logs and add them if they exist
          KERNEL_LOGS=$(find workflows/selftests/results/last-run -name "*.dmesg.log" 2>/dev/null)
          if [ -n "$KERNEL_LOGS" ]; then
            echo -e "Kernel tests results:\n" > ci.commit_extra
            for log in $KERNEL_LOGS; do
              if [ -s "$log" ]; then
                tail -n 1 "$log" >> ci.commit_extra
              fi
            done
            echo -e "\n\n" >> ci.commit_extra
          fi

          # Check for userspace test logs and add them if they exist
          USERSPACE_LOGS=$(find workflows/selftests/results/last-run -name "*.userspace.log" 2>/dev/null)
          if [ -n "$USERSPACE_LOGS" ]; then
            echo -e "Userspace test results:\n" >> ci.commit_extra
            for log in $USERSPACE_LOGS; do
              if [ -s "$log" ]; then
                echo "Results from $log:" >> ci.commit_extra
                tail -n 1 "$log" >> ci.commit_extra
              fi
            done
          fi

          ./scripts/workflows/generic/crash_report.py >> ci.commit_extra

          if grep -i -q "fail" ci.commit_extra || [ -d crash ]; then
            echo "fail" > ci.result
          else
            echo "ok" > ci.result
          fi

  cleanup:
    needs: [run-tests, setup]  # Add setup as a dependency to ensure proper ordering
    if: always()  # This ensures cleanup runs even if run-tests fails
    uses: ./.github/workflows/kdevops-cleanup.yml
    secrets: inherit
