# SPDX-License-Identifier: GPL-2.0
#
# Most simple Linux kernel subsystems can be tested with this target
# test setup. For more elaborates tests look for a topic branch under the
# kdevops-ci tree. For example to test a filesystem look at the fstests
# branch.

name: Run generic kdevops CI tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:  # Allow manual triggering

jobs:
  setup:
    uses: ./.github/workflows/kdevops-init.yml
    secrets: inherit

  run-tests:
    needs: setup
    name: Run CI tests
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Run CI tests
        run: |
          cd kdevops
          make ci-test

          echo -e "Kernel tests results:\n" > ci.commit_extra
          tail -n 1 workflows/selftests/results/last-run/*/*.dmesg.log >> ci.commit_extra
          echo -e "\n\n" >> ci.commit_extra
          echo -e "Userspace test results:\n" >> ci.commit_extra
          tail -n 1 workflows/selftests/results/last-run/*/*.userspace.log >> ci.commit_extra
          echo -e "\n\n" >> ci.commit_extra

          if grep -i -q "fail" ci.commit_extra ; then
            echo "fail" > ci.result
          else
            echo "ok" > ci.result
          fi

  cleanup:
    needs: run-tests
    uses: ./.github/workflows/kdevops-cleanup.yml
    secrets: inherit
