# SPDX-License-Identifier: GPL-2.0
---
name: Run kdevops CI Workflow - Manual

on:
  workflow_dispatch:
    inputs:
      ci_workflow:
        description: "CI Workflow"
        required: true
        default: 'blktests_nvme'
        type: choice
        options:
          - blktests
          - blktests_block
          - blktests_loop
          - blktests_meta
          - blktests_nbd
          - blktests_nvme
          - blktests_nvmemp
          - blktests_scsi
          - blktests_srp
          - blktests_zbd
          - tmpfs
          - tmpfs_default
          - tmpfs_huge
          - tmpfs_noswap
          - linux-btrfs-kpd
          - linux-ext4-kpd
          - linux-firmware-kpd
          - linux-mm-kpd
          - linux-modules-kpd
          - linux-xfs-kpd
          - selftests
      kernel_tree:
        description: "Linux kernel tree to use"
        required: true
        default: 'linux'
        type: choice
        options:
          - linux
          - linux-next
          - linux-stable
      kernel_ref:
        description: "Linux tree git reference (branch/tag/commit-id)"
        required: true
        default: 'master'
        type: string

jobs:
  check_ref:
    name: Check Linux kernel Git Reference
    runs-on: [self-hosted]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check kernel_ref exists
        id: check_kernel_ref
        run: |
          set -euxo pipefail

          ref="${{ github.event.inputs.kernel_ref }}"
          tree="${{ github.event.inputs.kernel_tree }}"
          mirror="/mirror/${tree}.git"
          ls_remote="$(git ls-remote "$mirror" "refs/*/${ref}" || true)"
          contains_branch="$(git -C "$mirror" branch --contains "${ref}" || true)"
          contains_tag="$(git -C "$mirror" branch --contains "${ref}" || true)"

          if [ -z "$ls_remote" ] && [ -z "$contains_branch" ] && [ -z "$contains_tag" ]; then
            echo "Linux kernel ${ref} does not exist."
            exit 1
          fi

  manual:
    name: Manual kdevops CI
    needs: [check_ref]
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      ci_workflow: ${{ inputs.ci_workflow }}
      kernel_ref: ${{ inputs.kernel_ref }}
      kernel_tree: ${{ inputs.kernel_tree }}
